### ISSUE TITLE
tox fails with pippy is not allowed

### ISSUE THREAD

**Issue by jaraco** [reubano/csv2ofx#102]
```
 csv2ofx master $ tox --version
4.5.2 from /Users/jaraco/.local/pipx/venvs/tox/lib/python3.11/site-packages/tox/__init__.py
 csv2ofx master $ tox
py: install_deps> helpers/pippy -r /Users/jaraco/code/reubano/csv2ofx/dev-requirements.txt -r /Users/jaraco/code/reubano/csv2ofx/requirements.txt
py: failed with /Users/jaraco/code/reubano/csv2ofx/helpers/pippy (resolves to /Users/jaraco/code/reubano/csv2ofx/helpers/pippy) is not allowed, use allowlist_externals to allow it
  py: FAIL code 1 (0.02 seconds)
  evaluation failed :( (0.05 seconds)
```

**Comment by jaraco** [comment]
I also tried running `manage test`, but it too failed as manage.py appears to be too old for Python 3.11:

```
 csv2ofx master $ pip-run manage.py -- -m manage test
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/jaraco/code/reubano/csv2ofx/manage.py", line 37, in <module>
    @manager.command
     ^^^^^^^^^^^^^^^
  File "/var/folders/sx/n5gkrgfx6zd91ymxr2sr9wvw00n8zm/T/pip-run-vwyhkjst/manager/__init__.py", line 251, in command
    return register(fn)
           ^^^^^^^^^^^^
  File "/var/folders/sx/n5gkrgfx6zd91ymxr2sr9wvw00n8zm/T/pip-run-vwyhkjst/manager/__init__.py", line 247, in register
    return wrapped(**kwargs)
           ^^^^^^^^^^^^^^^^^
  File "/var/folders/sx/n5gkrgfx6zd91ymxr2sr9wvw00n8zm/T/pip-run-vwyhkjst/manager/__init__.py", line 244, in wrapped
    command = self.Command(run=fn, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/folders/sx/n5gkrgfx6zd91ymxr2sr9wvw00n8zm/T/pip-run-vwyhkjst/manager/__init__.py", line 59, in __init__
    self.inspect()
  File "/var/folders/sx/n5gkrgfx6zd91ymxr2sr9wvw00n8zm/T/pip-run-vwyhkjst/manager/__init__.py", line 65, in inspect
    self.arg_names, varargs, keywords, defaults = inspect.getargspec(
                                                  ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
```

**Comment by jaraco** [comment]
[getargspec was removed in Python 3.11](https://docs.python.org/3.11/whatsnew/3.11.html#removed).
