### ISSUE TITLE
manage.py fails on Python 3.11

### ISSUE THREAD

**Issue by jaraco** [reubano/csv2ofx#103]
Trying to run `manage test`, it failed as manage.py appears to be too old for Python 3.11:

```
 csv2ofx master $ pip-run manage.py -- -m manage test
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/jaraco/code/reubano/csv2ofx/manage.py", line 37, in <module>
    @manager.command
     ^^^^^^^^^^^^^^^
  File "/var/folders/sx/n5gkrgfx6zd91ymxr2sr9wvw00n8zm/T/pip-run-vwyhkjst/manager/__init__.py", line 251, in command
    return register(fn)
           ^^^^^^^^^^^^
  File "/var/folders/sx/n5gkrgfx6zd91ymxr2sr9wvw00n8zm/T/pip-run-vwyhkjst/manager/__init__.py", line 247, in register
    return wrapped(**kwargs)
           ^^^^^^^^^^^^^^^^^
  File "/var/folders/sx/n5gkrgfx6zd91ymxr2sr9wvw00n8zm/T/pip-run-vwyhkjst/manager/__init__.py", line 244, in wrapped
    command = self.Command(run=fn, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/folders/sx/n5gkrgfx6zd91ymxr2sr9wvw00n8zm/T/pip-run-vwyhkjst/manager/__init__.py", line 59, in __init__
    self.inspect()
  File "/var/folders/sx/n5gkrgfx6zd91ymxr2sr9wvw00n8zm/T/pip-run-vwyhkjst/manager/__init__.py", line 65, in inspect
    self.arg_names, varargs, keywords, defaults = inspect.getargspec(
                                                  ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
```

[getargspec was removed in Python 3.11](https://docs.python.org/3.11/whatsnew/3.11.html#removed).

**Comment by sphakka** [comment]
I guess the project should drop Nose, as [stated in its doc page](https://nose.readthedocs.io/en/latest/index.html#note-to-users):
 
"Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership. New projects should consider using [Nose2](https://github.com/nose-devs/nose2), [py.test](http://pytest.org/), or just plain unittest/unittest2."

**Comment by jaraco** [comment]
The issue here isn't nose, but [manage.py](https://pypi.org/project/manage.py), which hasn't been updated since 2015, so definitely abandonware. That package also imports imp. So it has to go.
