### ISSUE TITLE
The imp module has been removed in python 3.12

### ISSUE THREAD

**Issue by zuzzurro** [reubano/csv2ofx#109]
```
Traceback (most recent call last):
  File "/home/paolo/.local/bin/csv2ofx", line 15, in <module>
    from csv2ofx.main import run
  File "/home/paolo/.local/lib/python3.12/site-packages/csv2ofx/main.py", line 25, in <module>
    from imp import find_module, load_module
ModuleNotFoundError: No module named 'imp'
```

https://discuss.python.org/t/how-do-i-migrate-from-imp/27885

No idea what to do next. Help! Fedora 39 moves to python 3.12 and that means I'm going to be unable to use csv2ofx

**Comment by Mat-VL** [comment]
exclude line 25 from main.py file.
this worked for me.

![LINE25](https://github.com/user-attachments/assets/4a283543-2b81-4871-9724-74a3221f1207)

**Comment by glowing-axolotl** [comment]
Hi there @jaraco @reubano ,

I noticed this issue has been stale for some time. Could I ask you if there are any updates? In case you are having issues (or are bound by the incessant passage of time), would you like me to help on this issue?

In the meantime for people reading this, you need to use a lower python version only if, like me, you are using the "--custom" option to point to a custom mapping in a .py file.

A discussion on the deprecation of imp can be found here https://discuss.python.org/t/how-do-i-migrate-from-imp/27885/27

If you have the knowledge to, you can use GNU Guix or NixOS to use an older python version.
For example with Nix using Python 3.10:
```
nix-shell -p python310
```

**Comment by jaraco** [comment]
I'd be glad to help. Unfortunately, I'm blocked on even developing on Python 3.12 due to https://github.com/reubano/csv2ofx/issues/111, which itself is blocked on https://github.com/reubano/meza/pull/63. I've re-opened #113 to address my access issues.

**Comment by reubano** [comment]
@glowing-axolotl please feel free to submit a PR and @jaraco can assist with getting an updated release. Thanks for the help!

**Comment by glowing-axolotl** [comment]
Awesome work, thanks @jaraco and @reubano

**Comment by jaraco** [comment]
The latest 0.31.0 release builds and runs on Python through 3.13.
