### ISSUE TITLE
pip install csv2ofx fails on Windows 11 with python.org 3.12.2 installed

### ISSUE THREAD

**Issue by so1dieroffortune** [reubano/csv2ofx#118]
I was a software developer in my previous life, but I'm not an experienced python user by any stretch. I have python 3.12.2 installed (from python.org) on a Windows 11 machine. I wanted to try to use csv2ofx, but I got stuck when trying to install these libraries. This is the error trace i get. Am I doing something wrong here? Have i missed any steps? or is this in fact broken?

```
PS C:\Users\xyz> python --version
Python 3.12.2

PS C:\Users\xyz> pip install csv2ofx
Collecting csv2ofx
  Using cached csv2ofx-0.30.0-py2.py3-none-any.whl.metadata (10 kB)
Collecting meza<0.47.0,>=0.46.0 (from csv2ofx)
  Using cached meza-0.46.0-py2.py3-none-any.whl.metadata (23 kB)
Collecting python-dateutil<3.0.0,>=2.7.2 (from csv2ofx)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting requests<3.0.0,>=2.18.4 (from csv2ofx)
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting chardet<4.0.0,>=3.0.4 (from meza<0.47.0,>=0.46.0->csv2ofx)
  Using cached chardet-3.0.4-py2.py3-none-any.whl.metadata (3.2 kB)
Collecting python-slugify<2.0.0,>=1.2.5 (from meza<0.47.0,>=0.46.0->csv2ofx)
  Using cached python-slugify-1.2.6.tar.gz (6.8 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting xlrd<2.0.0,>=1.1.0 (from meza<0.47.0,>=0.46.0->csv2ofx)
  Using cached xlrd-1.2.0-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting dbfread==2.0.4 (from meza<0.47.0,>=0.46.0->csv2ofx)
  Using cached dbfread-2.0.4-py2.py3-none-any.whl.metadata (3.6 kB)
Collecting ijson<3.0.0,>=2.3 (from meza<0.47.0,>=0.46.0->csv2ofx)
  Using cached ijson-2.6.1.tar.gz (29 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting beautifulsoup4<5.0.0,>=4.6.0 (from meza<0.47.0,>=0.46.0->csv2ofx)
  Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting PyYAML<6.0.0,>=4.2b1 (from meza<0.47.0,>=0.46.0->csv2ofx)
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
pip :   error: subprocess-exited-with-error
At line:1 char:1
+ pip install csv2ofx
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (  error: subprocess-exited-with-error:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

  
  Getting requirements to build wheel did not run successfully.
  exit code: 1
 
  [54 lines of output]
  running egg_info
  writing lib3\PyYAML.egg-info\PKG-INFO
  writing dependency_links to lib3\PyYAML.egg-info\dependency_links.txt
  writing top-level names to lib3\PyYAML.egg-info\top_level.txt
  Traceback (most recent call last):
    File "C:\Users\xyz\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_i
n_process.py", line 353, in <module>
      main()
    File "C:\Users\xyz\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_i
n_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\xyz\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_i
n_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\xyz\AppData\Local\Temp\pip-build-env-efnyeglc\overlay\Lib\site-packages\setuptools\build_meta.py", line
325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\xyz\AppData\Local\Temp\pip-build-env-efnyeglc\overlay\Lib\site-packages\setuptools\build_meta.py", line
295, in _get_build_requires
      self.run_setup()
    File "C:\Users\xyz\AppData\Local\Temp\pip-build-env-efnyeglc\overlay\Lib\site-packages\setuptools\build_meta.py", line
311, in run_setup
      exec(code, locals())
    File "<string>", line 271, in <module>
    File "C:\Users\xyz\AppData\Local\Temp\pip-build-env-efnyeglc\overlay\Lib\site-packages\setuptools\__init__.py", line
104, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\xyz\AppData\Local\Temp\pip-build-env-efnyeglc\overlay\Lib\site-packages\setuptools\_distutils\core.py",
line 185, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "C:\Users\xyz\AppData\Local\Temp\pip-build-env-efnyeglc\overlay\Lib\site-packages\setuptools\_distutils\core.py",
line 201, in run_commands
      dist.run_commands()
    File "C:\Users\xyz\AppData\Local\Temp\pip-build-env-efnyeglc\overlay\Lib\site-packages\setuptools\_distutils\dist.py",
line 969, in run_commands
      self.run_command(cmd)
    File "C:\Users\xyz\AppData\Local\Temp\pip-build-env-efnyeglc\overlay\Lib\site-packages\setuptools\dist.py", line 967,
in run_command
      super().run_command(command)
    File "C:\Users\xyz\AppData\Local\Temp\pip-build-env-efnyeglc\overlay\Lib\site-packages\setuptools\_distutils\dist.py",
line 988, in run_command
      cmd_obj.run()
    File
"C:\Users\xyz\AppData\Local\Temp\pip-build-env-efnyeglc\overlay\Lib\site-packages\setuptools\command\egg_info.py", line
321, in run
      self.find_sources()
    File
"C:\Users\xyz\AppData\Local\Temp\pip-build-env-efnyeglc\overlay\Lib\site-packages\setuptools\command\egg_info.py", line
329, in find_sources
      mm.run()
    File
"C:\Users\xyz\AppData\Local\Temp\pip-build-env-efnyeglc\overlay\Lib\site-packages\setuptools\command\egg_info.py", line
550, in run
      self.add_defaults()
    File
"C:\Users\xyz\AppData\Local\Temp\pip-build-env-efnyeglc\overlay\Lib\site-packages\setuptools\command\egg_info.py", line
588, in add_defaults
      sdist.add_defaults(self)
    File "C:\Users\xyz\AppData\Local\Temp\pip-build-env-efnyeglc\overlay\Lib\site-packages\setuptools\command\sdist.py",
line 102, in add_defaults
      super().add_defaults()
    File
"C:\Users\xyz\AppData\Local\Temp\pip-build-env-efnyeglc\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py",
line 251, in add_defaults
      self._add_defaults_ext()
    File
"C:\Users\xyz\AppData\Local\Temp\pip-build-env-efnyeglc\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py",
line 336, in _add_defaults_ext
      self.filelist.extend(build_ext.get_source_files())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<string>", line 201, in get_source_files
    File "C:\Users\xyz\AppData\Local\Temp\pip-build-env-efnyeglc\overlay\Lib\site-packages\setuptools\_distutils\cmd.py",
line 107, in __getattr__
      raise AttributeError(attr)
  AttributeError: cython_sources
  [end of output]
 
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
Getting requirements to build wheel did not run successfully.
exit code: 1
See above for output.
note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by montgomeryb** [comment]
It seems that meza is the culprit and that may have been fixed. However, I got around this problem running
`pip install --force-reinstall "PyYAML==5.1"
pip install meza
pip install csv2ofx`

**Comment by HupAndRunning** [comment]
Thank you montgomeryb.  I had the same problem and the workaround allowed me to build.

**Comment by lwilsontlu** [comment]
Thank you so much, montgomeryb!  I've been fighting the same issue for an hour and finally thought to look here.

**Comment by jaraco** [comment]
This issue should be fixed in the latest releases. csv2ofx was pinned to an old version of PyYAML that didn't have binary releases in PyPI for later Python versions. The latest releases now depend on newer PyYAML, which has wheels for PyYAML, so should install easily.
