### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode

### ISSUE THREAD

**Issue by gullitmiranda** [reubano/csv2ofx#13]
``` sh
$ csv2ofx -ov -l PT-BR extrato-201609071200.csv extrato-201609071200.ofx
Traceback (most recent call last):
  File "/usr/local/bin/csv2ofx", line 20, in <module>
    run()
  File "/usr/local/lib/python2.7/site-packages/csv2ofx/main.py", line 141, in run
    write(args.dest, IterStringIO(content), **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tabutils/io.py", line 691, in write
    return _write(filepath, content, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tabutils/io.py", line 679, in _write
    for c in ft.chunk(content, chunksize):
  File "/usr/local/lib/python2.7/site-packages/tabutils/fntools.py", line 248, in <genexpr>
    generator = (content.read(chunksize) for _ in it.count())
  File "/usr/local/lib/python2.7/site-packages/tabutils/io.py", line 110, in read
    return self._read(self.iter, n)
  File "/usr/local/lib/python2.7/site-packages/tabutils/io.py", line 103, in _read
    return ft.byte(it.islice(iterable, n)) if n else ft.byte(iterable)
  File "/usr/local/lib/python2.7/site-packages/tabutils/fntools.py", line 183, in byte
    tupled = tuple(content) if hasattr(content, 'next') else content
  File "/usr/local/lib/python2.7/site-packages/tabutils/io.py", line 96, in <genexpr>
    return (s.encode(ENCODING) for s in iterable)
  File "/usr/local/lib/python2.7/site-packages/csv2ofx/ofx.py", line 417, in gen_body
    for gd in data:
  File "/usr/local/lib/python2.7/site-packages/csv2ofx/utils.py", line 130, in gen_data
    for group, main_pos, sorted_trxns in groups:
  File "/usr/local/lib/python2.7/site-packages/csv2ofx/__init__.py", line 238, in clean_trxns
    for group, trxns in groups:
  File "/usr/local/lib/python2.7/site-packages/csv2ofx/__init__.py", line 224, in gen_trxns
    for group, transactions in groups:
  File "/usr/local/lib/python2.7/site-packages/csv2ofx/ofx.py", line 451, in gen_groups
    for chnk in chunk(records, chunksize):
  File "/usr/local/lib/python2.7/site-packages/tabutils/fntools.py", line 263, in <genexpr>
    generator = (list(it.islice(i, chunksize)) for _ in it.count())
  File "/usr/local/lib/python2.7/site-packages/tabutils/io.py", line 411, in read_csv
    for row in read_file(filepath):
  File "/usr/local/lib/python2.7/site-packages/tabutils/io.py", line 393, in read_file
    names = csv.reader(f, encoding=encoding, **kwargs).next()
  File "/usr/local/lib/python2.7/site-packages/unicodecsv/__init__.py", line 112, in next
    unicode_(value, encoding, encoding_errors)) for value in row]
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd3 in position 10: invalid continuation byte
```

sample file:

``` csv
"DATA";"HISTÓRICO DE DESPESAS";"TIPO";"VALOR"
"10/Ago";"COMPRA DÉBITO NACIONAL - SOME         -SAO PAULO-BRA";"Débito";"- R$ 999,99"
```

**Comment by reubano** [comment]
Turns out this is fixed for py3 but not py2. Need to push an upstream patch to meza to get py2 working.
