### ISSUE TITLE
Referencing columns using column_# does not work when csv2ofx is invoked with the Python library

### ISSUE THREAD

**Issue by simonmetcalfe** [reubano/csv2ofx#62]
I've been using csv2ofx successfully for some time with some custom mapping files and a bash script which runs cs2ofx using the **CLI interface**.

To go cross platform I re-wrote the bash script in Python and replaced the CLI with the Python library.  However now, any banks with mapping files that use **column_#** to reference the columns (because the CSV has no header) now fail.  Either the script fails with an error, or the field is just blank.

An example mapping file using column_# which now fails is:
```
from __future__ import (
    absolute_import, division, print_function, unicode_literals)

from operator import itemgetter

# Convert DD/MM/YYYY date to MM/DD/YYYY (the format required for csv2ofx)
def date_func(tr):
    date = tr['column_1']
    return '{}/{}/{}'.format(date[3:5], date[:2], date[-4:])

# Remove additional spaces
def remove_spaces(text):
    return " ".join(text.split())

mapping = {
    'has_header': False,
    'is_split': False,
    'bank': 'Citibank',
    'currency': 'AUD',
    'delimiter': ',',
    'date': date_func,
    'payee': lambda tr: remove_spaces(tr['column_2']),
    'amount': itemgetter('column_3'),
    'account': itemgetter('column_5')
}
```

The source data for this mapping looks like:
```
"03/07/2019","Miscellaneous BOOTS 2137             GATWICK       GBR","-8.13","","'123456789'"
"03/07/2019","Miscellaneous NEW SOUTHERN RAILW     HOVE 4038     GBR","-19.56","","'123456789'"
```

I invoke csv2ofx using the library and write the file to disk like so:
```
ofx = OFX(mapping)
records = read_csv(source_file)
groups = ofx.gen_groups(records)
trxns = ofx.gen_trxns(groups)
cleaned_trxns = ofx.clean_trxns(trxns)
data = utils.gen_data(cleaned_trxns)
content = it.chain([ofx.header(), ofx.gen_body(data), ofx.footer()])

# Save the file to disk
dest_file = source_file + ".ofx"
df = open(dest_file, "wb")
for line in IterStringIO(content):
    df.write(line)
    # print(line)
df.close()
```

The error response for the example above is:
```  
Traceback (most recent call last):
  File ".\csv2ofx-simon.py", line 170, in <module>
    for line in IterStringIO(content):
  File "C:\Users\simon\AppData\Local\Programs\Python\Python37\lib\site-packages\meza\io.py", line 113, in __next__
    return self._read(next(self.lines))
  File "C:\Users\simon\AppData\Local\Programs\Python\Python37\lib\site-packages\meza\io.py", line 123, in <genexpr>
    return (g for k, g in groups if k)
  File "C:\Users\simon\AppData\Local\Programs\Python\Python37\lib\site-packages\meza\io.py", line 66, in <genexpr>
    encode = lambda iterable: (s.encode(ENCODING) for s in iterable)
  File "C:\Users\simon\AppData\Local\Programs\Python\Python37\lib\site-packages\csv2ofx\ofx.py", line 444, in gen_body
    for datum in data:
  File "C:\Users\simon\AppData\Local\Programs\Python\Python37\lib\site-packages\csv2ofx\utils.py", line 152, in gen_data
    for group, main_pos, sorted_trxns in groups:
  File "C:\Users\simon\AppData\Local\Programs\Python\Python37\lib\site-packages\csv2ofx\__init__.py", line 294, in clean_trxns
    for grp, trxns in groups:
  File "C:\Users\simon\AppData\Local\Programs\Python\Python37\lib\site-packages\csv2ofx\__init__.py", line 280, in gen_trxns
    for grp, transactions in groups:
  File "C:\Users\simon\AppData\Local\Programs\Python\Python37\lib\site-packages\csv2ofx\ofx.py", line 484, in gen_groups
    for gee in group(cleansed, keyfunc):
  File "C:\Users\simon\AppData\Local\Programs\Python\Python37\lib\site-packages\meza\process.py", line 591, in group
    sorted_records = sorted(records, key=keyfunc)
KeyError: 'column_5'
```

The error response does vary depending on the first field to fails.  For example, if the account name is hard coded with `'account': 'Citibank'`, the error changes to:
```
Traceback (most recent call last):
  File ".\csv2ofx-simon.py", line 170, in <module>
    for line in IterStringIO(content):
  File "C:\Users\simon\AppData\Local\Programs\Python\Python37\lib\site-packages\meza\io.py", line 113, in __next__
    return self._read(next(self.lines))
  File "C:\Users\simon\AppData\Local\Programs\Python\Python37\lib\site-packages\meza\io.py", line 123, in <genexpr>
    return (g for k, g in groups if k)
  File "C:\Users\simon\AppData\Local\Programs\Python\Python37\lib\site-packages\meza\io.py", line 66, in <genexpr>
    encode = lambda iterable: (s.encode(ENCODING) for s in iterable)
  File "C:\Users\simon\AppData\Local\Programs\Python\Python37\lib\site-packages\csv2ofx\ofx.py", line 444, in gen_body
    for datum in data:
  File "C:\Users\simon\AppData\Local\Programs\Python\Python37\lib\site-packages\csv2ofx\utils.py", line 152, in gen_data
    for group, main_pos, sorted_trxns in groups:
  File "C:\Users\simon\AppData\Local\Programs\Python\Python37\lib\site-packages\csv2ofx\__init__.py", line 314, in clean_trxns
    sorted_trxns = sorted(enumerate(filtered_trxns), key=keyfunc)
  File "C:\Users\simon\AppData\Local\Programs\Python\Python37\lib\site-packages\csv2ofx\__init__.py", line 161, in skip_transaction
    return not self.end >= parse(self.get('date', trxn)) >= self.start
  File "C:\Users\simon\AppData\Local\Programs\Python\Python37\lib\site-packages\dateutil\parser\_parser.py", line 1358, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\simon\AppData\Local\Programs\Python\Python37\lib\site-packages\dateutil\parser\_parser.py", line 646, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\simon\AppData\Local\Programs\Python\Python37\lib\site-packages\dateutil\parser\_parser.py", line 722, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\simon\AppData\Local\Programs\Python\Python37\lib\site-packages\dateutil\parser\_parser.py", line 207, in split
    return list(cls(s))
  File "C:\Users\simon\AppData\Local\Programs\Python\Python37\lib\site-packages\dateutil\parser\_parser.py", line 76, in __init__
    '{itype}'.format(itype=instream.__class__.__name__))
TypeError: Parser must be a string or character stream, not NoneType
```

I've run out of ideas of how to solve this (other than by using the CLI instead of the Python library), so if anyone is able to help that would be great!

Thanks

**Comment by reubano** [comment]
You're missing the `has_header` kwarg.

https://github.com/reubano/csv2ofx/blob/0cf9432ab90dc1fc02237800592fce1462720037/csv2ofx/main.py#L194-L199

So, you would do something like this...

`records = read_csv(source_file, has_header=False)`
